# Generated by Django 4.0.3 on 2022-04-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_database_name_tenant_database_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='domain_url',
            field=models.URLField(),
        ),
    ]
