# Generated by Django 4.0.3 on 2022-04-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tenant_domain_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='domain_url',
            field=models.CharField(max_length=200),
        ),
    ]
